coloc/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r"^", include("shared.urls")),
    url(r'^count/', include('count.urls')),
    url(r"^notes/", include("notes.urls")),
    url(r'^logout/?$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^login/?$', auth_views.login,
        {'template_name': 'admin/login.html'},
        name="login",
        ),
    url(r'^admin/', admin.site.urls),
]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

count/urls.py
from django.conf.urls import url
from . import views

app_name = "count"
urlpatterns = [
    url(r'^historique/?$', views.historique, name='history'),
    url(r"^profile$", views.UserUpdate.as_view(), name="profile"),

    # Purchases
    url(r'^add/?$', views.DepenseCreate.as_view(), name='depense'),
    url(r'^modifDepense/(?P<pk>\d+)/?$',
        views.DepenseUpdate.as_view(),
        name='modif-depense'),

    # Transfers
    url(r'^rembourse/?$', views.RembourseCreate.as_view(), name='rembourse'),
    url(r'^modifRemboursement/(?P<pk>\d+)/?$',
        views.RembourseUpdate.as_view(),
        name='modif-rembourse')
]

count/models.py
from django.dispatch import receiver
from django.db import models, transaction
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from datetime import date


# ---
# Users
# ---

class Nous(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    solde = models.FloatField(default=0)
    absent = models.BooleanField(default=False)

    def __str__(self):
        return self.user.get_short_name()

    class Meta:
        verbose_name = "Nous"
        verbose_name_plural = "Nous"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Nous.objects.get_or_create(user=instance)


# ---
# Operations
# ---

class Depense(models.Model):
    montant = models.FloatField(default=0)
    personne = models.ForeignKey(
        Nous,
        on_delete=models.CASCADE,
        related_name="paie"
    )
    date = models.DateField(default=date.today)
    raison = models.CharField(max_length=200)
    beneficiaires = models.ManyToManyField(Nous)

    def apply_to_users(self, reverse=False):
        modifier = -1 if reverse else 1
        nb = self.beneficiaires.count()
        part = self.montant / nb
        with transaction.atomic():
            for b in self.beneficiaires.all():
                b.refresh_from_db()
                b.solde -= part * modifier
                b.save()
            self.personne.refresh_from_db()
            self.personne.solde += self.montant * modifier
            self.personne.save()

    def __str__(self):
        return "%s %s" % (str(self.date), self.raison)


class Rembourse(models.Model):
    payeur = models.ForeignKey(
        Nous,
        on_delete=models.CASCADE,
        related_name="payeur"
    )
    beneficiaire = models.ForeignKey(Nous, on_delete=models.CASCADE)
    montant = models.FloatField(default=0)
    date = models.DateField(default=date.today)

    class Meta:
        verbose_name = "Remboursement"
        verbose_name_plural = "Remboursements"

    def apply_to_users(self, reverse=False):
        modifier = -1 if reverse else 1
        with transaction.atomic():
            self.payeur.refresh_from_db()
            self.payeur.solde += self.montant * modifier
            self.payeur.save()
            self.beneficiaire.refresh_from_db()
            self.beneficiaire.solde -= self.montant * modifier
            self.beneficiaire.save()

    def __str__(self):
        return "%s %s -> %s" % (str(self.date), str(self.payeur),
                                str(self.beneficiaire))

count/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

from .models import Depense, Nous, Rembourse


class DepenseForm(forms.ModelForm):
    class Meta:
        model = Depense
        exclude = []
        widgets = {"raison": forms.Textarea()}

    beneficiaires = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        validators=[MinLengthValidator(1)],
        queryset=Nous.objects.select_related("user"),
        initial=lambda: Nous.objects.filter(absent=False)
    )


class RembourseForm(forms.ModelForm):
    class Meta:
        model = Rembourse
        exclude = []


class UserForm(forms.ModelForm):
    absent = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ["first_name", "last_name"]

    def save(self, *args, **kwargs):
        user = super().save(*args, **kwargs)
        user.profile.absent = self.cleaned_data["absent"]
        user.profile.save()
        return user

count/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.db.models import Sum
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import CreateView, UpdateView, FormView

from .forms import DepenseForm, RembourseForm, UserForm
from .models import Depense, Rembourse

from datetime import timedelta
from itertools import chain


def _all_depenses_prefetch():
    return (
        Depense.objects
        .select_related("personne", "personne__user")
        .prefetch_related("beneficiaires", "beneficiaires__user")
    )


def _all_rembourses_prefetch():
    return (
        Rembourse.objects
        .select_related(
            "payeur", "payeur__user", "beneficiaire", "beneficiaire__user"
        )
    )


@login_required
def historique(request):
    # Select/prefetch operations from database
    depenses = _all_depenses_prefetch()
    rembourses = _all_rembourses_prefetch()
    # Compute information for the user
    history = sorted(
        chain(depenses, rembourses),
        key=lambda instance: instance.date, reverse=True
    )
    dernier = (
        depenses
        .filter(date__gte=timezone.now().date() - timedelta(days=30))
        .aggregate(Sum("montant"))
        ["montant__sum"]
    )
    context = {
        "total": depenses.aggregate(Sum("montant"))["montant__sum"],
        "dernier": dernier,
        "history": history
    }
    return render(request, "count/historique.html", context)


class UserUpdate(FormView):
    template_name = "count/user_update.html"
    form_class = UserForm
    success_url = reverse_lazy("shared:home")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial["absent"] = self.request.user.profile.absent
        return initial

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


# ---
# Purchases
# ---

class DepenseCreate(LoginRequiredMixin, CreateView):
    form_class = DepenseForm
    model = Depense
    template_name = "count/addDepense.html"
    login_url = "login"
    success_url = reverse_lazy("shared:home")

    def get_initial(self):
        initial = super().get_initial()
        initial["personne"] = self.request.user.profile
        return initial

    def form_valid(self, form):
        response = super().form_valid(form)
        self.object.apply_to_users()
        return response


class DepenseUpdate(LoginRequiredMixin, UpdateView):
    form_class = DepenseForm
    model = Depense
    template_name = "count/modifDepense.html"
    login_url = "login"
    success_url = reverse_lazy("shared:home")

    def form_valid(self, form):
        # Revert the effect of the purchase
        old_depense = Depense.objects.get(id=self.object.id)
        old_depense.apply_to_users(reverse=True)
        # Save an apply the purchase to the users
        response = super().form_valid(form)
        self.object.apply_to_users()
        return response


# ---
# Transfers
# ---

class RembourseCreate(LoginRequiredMixin, CreateView):
    form_class = RembourseForm
    model = Rembourse
    template_name = "count/addRembourse.html"
    login_url = "login"
    success_url = reverse_lazy("shared:home")

    def get_initial(self):
        initial = super().get_initial()
        initial["payeur"] = self.request.user.profile
        return initial

    def form_valid(self, form):
        response = super().form_valid(form)
        self.object.apply_to_users()
        return response


class RembourseUpdate(LoginRequiredMixin, UpdateView):
    form_class = RembourseForm
    model = Rembourse
    template_name = "count/modifRembourse.html"
    login_url = "login"
    success_url = reverse_lazy("shared:home")

    def form_valid(self, form):
        # Revert the effect of the transfer
        old_rembourse = Rembourse.objects.get(id=self.object.id)
        old_rembourse.apply_to_users(reverse=True)
        # Save an apply the transfer to the users
        response = super().form_valid(form)
        self.object.apply_to_users()
        return response

count/templates/count/addDepense.html
{% extends "shared/base_form.html" %}

{% block title %}Ajouter une dépense{% endblock %}
{% block form_title %}Ajouter une dépense{% endblock %}

count/templates/count/addRembourse.html
{% extends "shared/base_form.html" %}

{% block title %}Effectuer un remboursement{% endblock %}
{% block form_title %}Effectuer un remboursement{% endblock %}

count/templates/count/historique.html
{% extends "shared/base.html" %}
{% block titre %}Historique{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1>Historique</h1>

      <hr />

      <div class="row">
        <div class="col-md-6">
          <p>Dépenses sur les 30 derniers jours&nbsp;: {{ dernier }}</p>
        </div>
        <div class="col-md-6">
          <p>Dépenses totales&nbsp;: {{ total }}</p>
        </div>
      </div>

      <hr />

      {% include "count/history_table.html" %}
    </div>
  </div>

{% endblock %}

count/templates/count/history_table.html
{% load count_filters %}

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Montant</th>
      <th>Payeur</th>
	    <th>Raison</th>
	    <th>Bénéficiaires</th>
	    <th></th>
	  </tr>
	</thead>
	<tbody>
	  {% for h in history %}
	    <tr>
	      <td>{{ h.date }}</td>
	      <td>{{ h.montant }}</td>
	      {% with h|classname as modelclass %}
	      {% if modelclass == "Depense" %}
	        <td>{{ h.personne }}</td>
	        <td>{{ h.raison }}</td>
		<td>{{ h.beneficiaires.all | join_personnes }}</td>
	        <td>
	          <a href="{% url "count:modif-depense" h.id %}">
	            <span class="glyphicon glyphicon-pencil"></span>
	          </a>
	        </td>
	      {% elif modelclass == "Rembourse" %}
	        <td>{{ h.payeur }}</td>
	        <td>Remboursement</td>
	        <td>{{ h.beneficiaire }}</td>
	        <td><a href="{% url "count:modif-rembourse" h.id %}">Modifier</a></td>
	      {% endif %}
	      {% endwith %}
	    </tr>
	  {% endfor %}
	</tbody>
</table>

count/templates/count/history_table_condensed.html
{% load count_filters %}

<table class="table">
  <thead>
    <th>Date</th>
    <th>Montant</th>
    <th>Payeur</th>
	  <th>Raison</th>
	  <th></th>
  </thead>
	<tbody>
	  {% for h in history %}
	    <tr>
	      <td>{{ h.date|date:"d/M" }}</td>
	      <td>{{ h.montant }}</td>
	      {% with h|classname as modelclass %}
	      {% if modelclass == "Depense" %}
	        <td>{{ h.personne }}</td>
	        <td>{{ h.raison }}</td>
		<td>{{ h.beneficiaires.all | join_personnes }}</td>
	      {% elif modelclass == "Rembourse" %}
	        <td>{{ h.payeur }}</td>
	        <td>Remboursement</td>
	        <td>{{ h.beneficiaire }}</td>
	      {% endif %}
	      {% endwith %}
	    </tr>
	  {% endfor %}
	</tbody>
</table>

count/templates/count/home.html
{% extends "shared/base.html" %}
{% load count_filters %}

{% block titre %}Bilan{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-5 col-md-offset-1">
      <h2>Bilan</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Nom</th>
            <th>Solde</th>
          </tr>
        </thead>
        <tbody>
          {% for p in personnes %}
          <tr class="{% if p.absent %}
                       text-muted active
                     {% else %}
                       {% if p.solde > 0 %}
                         positive
                       {% else %}
                         negative
                       {% endif %}
                     {% endif %}">
              <td>{{ p }}</td>
              <td>{{ p.solde }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      {% if total > 0.2 or total < -0.2 %}
        <p>Le total, il chie dans la colle</p>
      {% endif %}
    </div>
    <div class="col-md-5 text-center">
      <h3>{{ user.get_short_name }}</h3>
      {% if user.profile.absent %}
        <span class="text-muted"><strong>Absent·e</strong></span>
      {% else %}
        <span class="text-success"><strong>Présent·e</strong></span>
      {% endif %}
      <span><a href="{% url 'count:profile' %}">Modifier</a><span>
    </div>

  </div>

  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2>Historique récent</h2>
      {% include "count/history_table.html" %}
    </div>
  </div>
{% endblock %}

count/templates/count/modifDepense.html
{% extends "shared/base_form.html" %}

{% block title %}Modifier une dépense{% endblock %}
{% block form_title %}Modifier une dépense{% endblock %}

count/templates/count/modifRembourse.html
{% extends "shared/base_form.html" %}

{% block title %}Modifier un remboursement{% endblock %}
{% block form_title %}Modifier un remboursement{% endblock %}

count/templates/count/user_update.html
{% extends "shared/base_form.html" %}

{% block title %}Modifier son profil{% endblock %}
{% block form_title %}Modifier son profil{% endblock %}