coloc/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r"^", include("shared.urls")),
    url(r'^count/', include('count.urls')),
    url(r"^notes/", include("notes.urls")),
    url(r'^logout/?$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^login/?$', auth_views.login,
        {'template_name': 'admin/login.html'},
        name="login",
        ),
    url(r'^admin/', admin.site.urls),
]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

count/urls.py
from django.conf.urls import url
from . import views

app_name = "count"
urlpatterns = [
    url(r'^historique/?$', views.historique, name='history'),
    url(r"^profile$", views.UserUpdate.as_view(), name="profile"),

    # Purchases
    url(r'^add/?$', views.DepenseCreate.as_view(), name='depense'),
    url(r'^modifDepense/(?P<pk>\d+)/?$',
        views.DepenseUpdate.as_view(),
        name='modif-depense'),

    # Transfers
    url(r'^rembourse/?$', views.RembourseCreate.as_view(), name='rembourse'),
    url(r'^modifRemboursement/(?P<pk>\d+)/?$',
        views.RembourseUpdate.as_view(),
        name='modif-rembourse')
]

notes/urls.py
from django.conf.urls import url
from . import views

app_name = "notes"
urlpatterns = [
    url(r"^list$", views.notes_list, name="list"),
    url(r"^new$", views.note_create, name="new"),
    url(r"^edit/(?P<pk>\d+)$", views.note_update, name="update"),
]

shared/urls.py
from django.conf.urls import url
from . import views

app_name = "shared"
urlpatterns = [
    url(r"^$", views.home, name="home"),
]

shared/models.py
from django.db import models

# Create your models here.

shared/views.py
from itertools import chain

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from count.views import _all_depenses_prefetch, _all_rembourses_prefetch
from notes.models import Note

User = get_user_model()


@login_required
def home(request):
    depenses = _all_depenses_prefetch().order_by("-date")[:10]
    rembourses = _all_rembourses_prefetch().order_by("-date")[:10]
    history = sorted(
        chain(depenses, rembourses),
        key=lambda instance: instance.date, reverse=True
    )[:10]
    personnes = (
        User.objects
        .select_related("profile")
        .order_by("profile__absent", "-profile__solde")
    )
    notes = (
        Note.objects
        .order_by("-date")
        .select_related("author")
        [:5]
    )
    context = {
        "notes": notes,
        "personnes": personnes,
        "total": sum(p.profile.solde for p in personnes),
        "history": history
    }
    return render(request, "shared/home.html", context)

shared/templates/shared/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block titre %}{%endblock%}</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
        integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
        crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
          integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
          crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'css/perso.css' %}"/>

  {% block extrahead %}{% endblock %}
</head>
<body>
  <div id="page" class="container-fluid">
    <div class="row nav-row">
      <div class="col-md-12">
        <nav class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url "shared:home" %}">
                <span class="glyphicon glyphicon-home"></span>
              </a>
            </li>
            <li><a href="{% url "count:history" %}">Historique</a></li>
            <li><a href="{% url "count:depense" %}">Dépense</a></li>
            <li><a href="{% url "count:rembourse" %}">Remboursement</a></li>
            <li>
              <a href="{% url "logout" %}">
                <span class="glyphicon glyphicon-log-out"></span>
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    {% block content %}
    {% endblock %}
  </div>
</body>

shared/templates/shared/base_form.html
{% extends "shared/base.html" %}
{% load bootstrap %}

{% block content %}
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>{% block form_title %}{% endblock %}</h2>
    <form role="form" method="post" action="">
      {% csrf_token %}
      {{ form | bootstrap }}
      <input class="btn btn-primary" type="submit" value="Enregistrer"/>
    </form>
  </div>
</div>
{% endblock %}

shared/templates/shared/home.html
{% extends "shared/base.html" %}
{% block titre %}Coloc{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-9">
      <div>
        <h2>Bilan</h2>
        <table class="table">
          <thead>
            <tr>
              <th>Nom</th>
              <th>Solde</th>
            </tr>
          </thead>
          <tbody>
            {% for u in personnes %}
            {% with p=u.profile %}
            <tr class="{% if p.absent %}
                         text-muted active
                       {% else %}
                         {% if p.solde > 0 %}
                           positive
                         {% else %}
                           negative
                         {% endif %}
                       {% endif %}">
                <td>{{ p }}</td>
                <td>{{ p.solde }}</td>
              </tr>
            {% endwith %}
            {% endfor %}
          </tbody>
        </table>

        {% if total > 0.1 or total < -0.1 %}
          <p>Le total, il chie dans la colle</p>
        {% endif %}
      </div> <!-- Bilan -->

      <div>
        <h2>Historique récent</h2>
        {% include "count/history_table_condensed.html" %}
      </div> <!-- Historique récent -->
    </div> <!-- Count stuff -->

    <div class="col-md-3">
      <h2>Notes</h2>
      {% include "notes/list_condensed.html" %}

      <hr />

      <a href="{% url 'notes:list' %}">
        <button type="button" class="btn btn-default">
          <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
          Liste complète
        </button>
      </a>
      <a href="{% url 'notes:new' %}">
        <button type="button" class="btn btn-default">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
          Nouvelle note
        </button>
      </a>
    </div> <!-- Notes -->
  </div> <!-- row -->
{% endblock %}