coloc/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r"^", include("shared.urls")),
    url(r'^count/', include('count.urls')),
    url(r"^notes/", include("notes.urls")),
    url(r'^logout/?$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^login/?$', auth_views.login,
        {'template_name': 'admin/login.html'},
        name="login",
        ),
    url(r'^admin/', admin.site.urls),
]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

notes/urls.py
from django.conf.urls import url
from . import views

app_name = "notes"
urlpatterns = [
    url(r"^list$", views.notes_list, name="list"),
    url(r"^new$", views.note_create, name="new"),
    url(r"^edit/(?P<pk>\d+)$", views.note_update, name="update"),
]

notes/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()


class Note(models.Model):
    author = models.ForeignKey(User)
    date = models.DateTimeField(default=timezone.now)
    content = models.TextField("Note")

    def __str__(self):
        return "{} - {}".format(self.author, self.date)

notes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView

from custommail.shortcuts import send_mass_custom_mail

from .models import Note

User = get_user_model()


class NotesList(LoginRequiredMixin, ListView):
    model = Note
    template_name = "notes/listall.html"
    context_object_name = "notes"

    def get_queryset(self):
        return (
            Note.objects
            .order_by("-date")
            .select_related("author")
        )

notes_list = NotesList.as_view()


class NoteCreate(LoginRequiredMixin, CreateView):
    model = Note
    fields = ["author", "date", "content"]
    template_name = "notes/new.html"
    login_url = "login"
    success_url = reverse_lazy("shared:home")

    def form_valid(self, form):
        context = {"note": form.instance}
        datatuple = [
            ("note-notif", context, "coloc@wkerl.me", [u.email])
            for u in User.objects.all()
        ]
        send_mass_custom_mail(datatuple)
        return super().form_valid(form)

note_create = NoteCreate.as_view()


class NoteUpdate(LoginRequiredMixin, UpdateView):
    model = Note
    fields = ["author", "date", "content"]
    template_name = "notes/update.html"
    login_url = "login"
    success_url = reverse_lazy("shared:home")

note_update = NoteUpdate.as_view()

notes/templates/notes/list.html
{% for note in notes %}
  <div class="row">
    <div class="col-md-11">
      <blockquote>
        <p>{{ note.content|linebreaks }}</p>
        <footer>{{ note.author }}, {{ note.date|date:"j F Y" }}</footer>
      </blockquote>
    </div>

    <div class="col-md-1">
      <a href="{% url 'notes:update' note.pk %}">
        <button type="button" class="btn btn-default">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        </button>
      </a>
    </div>
  </div>
{% endfor %}

notes/templates/notes/list_condensed.html
{% for note in notes %}
  <blockquote>
    <p>{{ note.content|linebreaks }}</p>
    <footer>{{ note.author }}, {{ note.date|date:"j F Y" }}</footer>
  </blockquote>
{% endfor %}

notes/templates/notes/listall.html
{% extends "shared/base.html" %}
{% block titre %}Notes{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Notes</h1>

      <hr />

      {% include "notes/list.html" %}
    </div> <!-- Notes -->
  </div> <!-- row -->
{% endblock %}

notes/templates/notes/new.html
{% extends "shared/base_form.html" %}

{% block title %}Créer une note{% endblock %}
{% block form_title %}Créer une note{% endblock %}

notes/templates/notes/update.html
{% extends "shared/base_form.html" %}

{% block title %}Modifier une note{% endblock %}
{% block form_title %}Modifier une note{% endblock %}